services:
  postgres-spring-batch:
    image: 'postgres:latest'
    container_name: 'postgres-spring-batch'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - './docker/db-data:/var/lib/postgresql/data'